@api = http://localhost:3100

### Mostrar lista de carrito
GET {{ api }}/clients/

### Mostrar lista de carrito
POST {{ api }}/clients
Content-Type: application/json

{
  "id": 16,
  "name": "Emily Davis",
  "email": "emilydavis@email.com",
  "telephone": "4221117878",
  "username": "emilydavis",
  "password": "davis878"
}

### Actualizar algunos datos de usuario por id 
PATCH {{ api }}/clients/5
Content-Type: application/json

{
  "email": "dwilson@email.com"
}

### Eliminar a un usuario por id 
DELETE {{ api }}/clients/16

### Mostrar lista de carrito
GET {{ api }}/carts/

### Mostrar datos de un carrito
GET {{ api }}/carts/5

### borrar carrito
DELETE {{ api }}/carts/6

