@api = http://localhost:3100

### Mostrar lista de proveedres
GET {{ api }}/providers

### Mostrar datos de un proveedor por id
GET {{ api }}/providers/5

## Crear un nuevo proveedor
POST {{ api }}/providers
Content-Type: application/json

{
  "id": 2,
  "name": "",
  "email": "",
  "telephone": "",
  "username": "",
  "password": ""
}

### Actualizar algunos datos de proveedor por id 
PATCH {{ api }}/providers/4
Content-Type: application/json

{
  "email": "janesmith@email.com"
}

### borrar proveedor por id
DELETE {{ api }}/providers/2