@api = http://localhost:3100

### Mostrar lista de proveedres
GET {{ api }}/providers

### Mostrar datos de un proveedor por id
GET {{ api }}/providers/5

### Crear un nuevo proveedor
POST {{ api }}/providers
Content-Type: application/json

{
  "id": 6,
  "name": "Maria Ferman",
  "email": "mariaferman@email.com",
  "telephone": "0994582002",
  "username": "mariaferman",
  "password": "123456fm"
}

### Actualizar algunos datos de proveedor por id 
PATCH {{ api }}/providers/6
Content-Type: application/json

{
  "email": "mferman@email.com"
}

### borrar proveedor por id
DELETE {{ api }}/providers/5