@api = http://localhost:3100

### Mostrar lista de usuarios
GET {{ api }}/users/

### Crear un nuevo usuario 
POST {{ api }}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQzLCJ1c2VyIjoiYW1hbmRhYmVja2VyIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjk5NTgxODc2MDI5LCJpYXQiOjE2OTk1NzgyNzZ9.KDiSyzc1yJGOh5s92Y5nCtYpZWtd_kxNcSIZUuQaK7I

{
  "id": 22,
  "role": "provider",
  "name": "Oscar Salazar",
  "email": "oscarsalazar@gmail.com",
  "telephone": "6904440111",
  "username": "oslazar",
  "password": "salazar123"
}


### Actualizar algunos datos de usuario por id 
PUT {{ api }}/users/25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ0LCJ1c2VyIjoic29maWFyb2RyaWd1ZXoiLCJyb2xlIjoiY2xpZW50IiwiZXhwIjoxNjk5NTgxNjA4ODg2LCJpYXQiOjE2OTk1NzgwMDh9.qEYaGyfYq_Mc_qzo6noczA6mJJhQO78YsK1qhoFbbN4

{
  "email": "janesmith@email.com"
}

### Eliminar a un usuario por id 
DELETE {{ api }}/users/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ0LCJ1c2VyIjoic29maWFyb2RyaWd1ZXoiLCJyb2xlIjoiY2xpZW50IiwiZXhwIjoxNjk5NTgxNjA4ODg2LCJpYXQiOjE2OTk1NzgwMDh9.qEYaGyfYq_Mc_qzo6noczA6mJJhQO78YsK1qhoFbbN4


### Mostrar datos de un usuario por id
GET {{ api }}/users/24

### Mostrar el nombre del usuario por id 
GET {{ api }}/users/26/name

### Autenticar un usuario
POST {{ api }}/auth
Content-Type: application/json

{
  "username": "amandabecker",
  "password": "becker333"
}